# Copy this to .streamlit/secrets.toml locally and fill real values.
page_title = "Providers"
sidebar_state = "expanded"
page_left_padding_px = "20"

# Turso / libsql connection
TURSO_DATABASE_URL = "libsql://YOUR-DB.turso.io"
TURSO_AUTH_TOKEN = "YOUR_TOKEN"

# Admin password (only used by app_admin.py)
ADMIN_PASSWORD = "changeme"
